In [1]:
import pandas as pd
df=pd.read_csv("1000_Companies.csv")

In [2]:
df.head()

R&D_Spend  Administration  Marketing_Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [54]:
df.head()

R&D_Spend  Administration  Marketing_Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [38]:
a=df

In [6]:
df.isna().sum() #### Shows boolen values

R&D_Spend          5
Administration     4
Marketing_Spend    0
State              0
Profit             0
dtype: int64

In [7]:
df['R&D_Spend']=df['R&D_Spend'].ffill()

In [17]:
df['Administration']=df['Administration'].bfill()

In [39]:
a.isna().sum()

R&D_Spend          5
Administration     4
Marketing_Spend    0
State              0
Profit             0
dtype: int64

In [19]:
df.to_csv('cleaned_R&D.csv')
d1 = df

In [20]:
df['R&D_Spend']=df['R&D_Spend'].bfill()

In [21]:
d1.head()

R&D_Spend  Administration  Marketing_Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [23]:
df.to_csv('F:\DATA SCIENCE\cleaned_R&D.csv')

In [15]:
df['Administration']=df['Administration'].bfill()

In [16]:
df.isna().sum()

R&D_Spend          0
Administration     0
Marketing_Spend    0
State              0
Profit             0
dtype: int64

In [30]:
df['Administration']=df['Administration'].fillna(df.Administration.mean())

In [31]:
df.isna().sum()

R&D_Spend          0
Administration     0
Marketing_Spend    0
State              0
Profit             0
dtype: int64

In [42]:
a['R&D_Spend']=a['R&D_Spend'].fillna(a['R&D_Spend'].median())

In [43]:
a.isna().sum()

R&D_Spend          0
Administration     4
Marketing_Spend    0
State              0
Profit             0
dtype: int64

In [45]:
a.dropna(axis=0,inplace=True)

In [46]:
a.shape

(996, 5)

In [49]:
b=df

In [50]:
b.isna().sum()

R&D_Spend          5
Administration     4
Marketing_Spend    0
State              0
Profit             0
dtype: int64

In [51]:
b.dropna(axis=1,inplace=True)

In [52]:
b.shape

(1000, 3)

In [56]:
df1=df

In [57]:
a=df1

In [58]:
a.isna().sum()

R&D_Spend          5
Administration     4
Marketing_Spend    0
State              0
Profit             0
dtype: int64

In [59]:
a=a.fillna(0)

In [60]:
a.isna().sum()

R&D_Spend          0
Administration     0
Marketing_Spend    0
State              0
Profit             0
dtype: int64

In [62]:
a.State.unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [64]:
x=a[['R&D_Spend','Administration','Marketing_Spend']]

In [65]:
x.head()

R&D_Spend  Administration  Marketing_Spend
0  165349.20       136897.80        471784.10
1  162597.70       151377.59        443898.53
2  153441.51       101145.55        407934.54
3  144372.41       118671.85        383199.62
4  142107.34        91391.77        366168.42

In [67]:
y=a.Profit

In [68]:
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [71]:
x_train.shape,x_test.shape

((700, 3), (300, 3))

In [72]:
y_train.shape,y_test.shape

((700,), (300,))

In [73]:
from sklearn.linear_model import LinearRegression

In [74]:
model=LinearRegression()

In [76]:
model_train=model.fit(x_train,y_train)  ###Trained the model

In [78]:
model_train.coef_ ###If x change then y change prapotionaly ###y=mx+c Here it is m

array([0.57030862, 0.67262862, 0.09672885])

In [80]:
from sklearn.metrics import r2_score ### For accuracy Check

In [82]:
model_train.intercept_  ####y=mx+c Here it is C

-30997.66046982353

In [84]:
x1=30000
x2=40000
x3=80000

In [85]:
y=0.57030862*x1+0.67262862*x2+0.09672885*x3-30997.66046982353

In [86]:
y

20755.05093017647

In [87]:
pred=model_train.predict(x_test) ###Prediction on test 

In [88]:
pred

array([ 78615.11358734, 166520.37884427, 118432.32235894, 163118.36230486,
       107486.44320237, 156685.95643454,  85784.78003651, 158313.75247383,
        79295.85940331, 174728.71788001, 168452.15571624, 185178.80853552,
        73311.29014576,  60925.99743962, 102393.26563218, 168572.03546095,
       160423.63636482,  68435.60867557, 104450.0599467 , 101427.99310043,
        59637.45521124, 163662.95897874,  76425.59524987, 161178.02262557,
       113951.38785779,  95322.07184216, 145657.01778928, 165884.15980712,
       170074.81399042, 109834.37412894, 162604.5918853 ,  98510.01739104,
       100358.73470707, 100342.46531936,  93505.8933785 , 177121.17550847,
       153294.21529082, 176209.23302007, 164735.88287152,  89082.32993441,
        75455.42541022,  99431.37905788,  78824.04688002, 109479.01623121,
        61056.15264824,  96565.3963081 ,  88027.38795044,  50992.24607849,
       157316.18154692, 121879.53838713, 146216.17127218, 145179.21127397,
       178056.23774773,  

In [89]:
pred.shape

(300,)

In [91]:
r2_score(y_test,pred) ####Accuracy to check

0.8942385795413494

In [92]:
y_test

515     77629.44849
990    165330.14630
185    117353.99720
376    161936.04670
772    106433.59060
           ...     
758     52276.64348
32      97427.84000
150    108917.01570
638     56620.71510
858    102771.24350
Name: Profit, Length: 300, dtype: float64

In [93]:
from sklearn import preprocessing

In [94]:
le=preprocessing.LabelEncoder()

In [95]:
le.fit(df['State'])

LabelEncoder()

In [96]:
list(le.classes_) ###forchecking character

['California', 'Florida', 'New York']

In [98]:
df['State']=le.transform(df['State'])

In [99]:
df.head()

R&D_Spend  Administration  Marketing_Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [100]:
list(le.inverse_transform([2,2,1])) #### For check lebeling

['New York', 'New York', 'Florida']

In [4]:
df1=df.State

In [5]:
df1.isna().sum()

0

In [6]:
df1

0        New York
1      California
2         Florida
3        New York
4         Florida
          ...    
995    California
996    California
997    California
998    California
999      New York
Name: State, Length: 1000, dtype: object

In [7]:
df1.unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [9]:
lb=LabelEncoder()

In [10]:
integer_encoded=lb.fit_transform(df1)

In [11]:
integer_encoded

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2,
       0, 2, 1, 2, 0, 2, 1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0,
       2, 0, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 0, 1, 2, 0,
       1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 0, 1, 2, 1, 2, 1, 2,
       0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0, 2, 0, 1, 2,
       1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 0,
       1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 0,
       2, 0, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0,
       2, 1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0,
       2, 0, 2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1,
       2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1,
       0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0, 0, 1,

In [12]:
lb.inverse_transform([1,0,2,0])

array(['Florida', 'California', 'New York', 'California'], dtype=object)

In [14]:
lb=integer_encoded.reshape(len(integer_encoded),1)
lb

array([[2],
       [0],
       [1],
       [2],
       [1],
       [2],
       [0],
       [1],
       [2],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [0],
       [2],
       [1],
       [1],
       [2],
       [0],
       [1],
       [2],
       [1],
       [2],
       [1],
       [2],
       [0],
       [1],
       [0],
       [2],
       [1],
       [0],
       [2],
       [0],
       [0],
       [1],
       [0],
       [2],
       [0],
       [2],
       [1],
       [0],
       [2],
       [0],
       [2],
       [0],
       [1],
       [2],
       [1],
       [2],
       [0],
       [1],
       [2],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [0],
       [2],
       [1],
       [1],
       [2],
       [0],
       [1],
       [2],
       [1],
       [2],
       [1],
       [2],
       [0],
    

In [15]:
onc=OneHotEncoder(sparse=False)

In [17]:
onehotencoder=onc.fit_transform(lb)
onehotencoder

C:\anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [21]:
onehotencoder=onc.fit_transform(lb)
onehotencoder[1]

C:\anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([1., 0., 0.])

In [23]:
df2=pd.DataFrame(onehotencoder,columns=['California','Florida','New York'])
df2

California  Florida  New York
0           0.0      0.0       1.0
1           1.0      0.0       0.0
2           0.0      1.0       0.0
3           0.0      0.0       1.0
4           0.0      1.0       0.0
..          ...      ...       ...
995         1.0      0.0       0.0
996         1.0      0.0       0.0
997         1.0      0.0       0.0
998         1.0      0.0       0.0
999         0.0      0.0       1.0

[1000 rows x 3 columns]

In [24]:
new_df=df.join(df2)
new_df

R&D_Spend  Administration  Marketing_Spend       State        Profit  \
0    165349.20      136897.800      471784.1000    New York  192261.83000   
1    162597.70      151377.590      443898.5300  California  191792.06000   
2    153441.51      101145.550      407934.5400     Florida  191050.39000   
3    144372.41      118671.850      383199.6200    New York  182901.99000   
4    142107.34       91391.770      366168.4200     Florida  166187.94000   
..         ...             ...              ...         ...           ...   
995   54135.00      118451.999      173232.6695  California   95279.96251   
996  134970.00      130390.080      329204.0228  California  164336.60550   
997  100275.47      241926.310      227142.8200  California  413956.48000   
998  128456.23      321652.140      281692.3200  California  333962.19000   
999  161181.72      270939.860      295442.1700    New York  476485.43000   

     California  Florida  New York  
0           0.0      0.0       1.0  
1           1.0      0.0       0.0  
2           0.0      1.0       0.0  
3           0.0      0.0       1.0  
4           0.0      1.0       0.0  
..          ...      ...       ...  
995         1.0      0.0       0.0  
996         1.0      0.0       0.0  
997         1.0      0.0       0.0  
998         1.0      0.0       0.0  
999         0.0      0.0       1.0  

[1000 rows x 8 columns]

In [29]:
x=new_df[['Administration','California','Florida']]
x

Administration  California  Florida
0        136897.800         0.0      0.0
1        151377.590         1.0      0.0
2        101145.550         0.0      1.0
3        118671.850         0.0      0.0
4         91391.770         0.0      1.0
..              ...         ...      ...
995      118451.999         1.0      0.0
996      130390.080         1.0      0.0
997      241926.310         1.0      0.0
998      321652.140         1.0      0.0
999      270939.860         0.0      0.0

[1000 rows x 3 columns]